# Generated by Django 3.0.4 on 2020-03-11 09:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('unknown', 'Unknown')], max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Genderless', 'Genderless'), ('unknown', 'Unknown')], max_length=50)),
                ('episode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('url', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('dimension', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('residents', models.ManyToManyField(related_name='residents', to='c130.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='c130.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='c130.Location'),
        ),
    ]
