# Generated by Django 3.0.4 on 2020-03-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0004_auto_20200312_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
