# Generated by Django 3.0.4 on 2020-03-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0006_auto_20200312_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='residents',
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='c130.Location'),
        ),
    ]
