# Generated by Django 3.0.4 on 2020-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0008_auto_20200312_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='localImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
