# Generated by Django 3.0.4 on 2020-03-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0010_auto_20200313_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
