# Generated by Django 3.0.4 on 2020-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0011_auto_20200316_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
