# Generated by Django 3.0.4 on 2020-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0012_auto_20200316_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='c130.Episode', verbose_name='Episodes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
