# Generated by Django 3.0.4 on 2020-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0013_auto_20200317_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='Characters', to='c130.Character'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='dimension',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
