# Generated by Django 3.0.4 on 2020-03-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0014_auto_20200317_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='api_id',
            field=models.IntegerField(blank=True, error_messages={'unique': 'Character name already exists'}, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='localImage',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
