# Generated by Django 3.0.4 on 2020-03-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c130', '0016_auto_20200317_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='localImage',
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='profile1.jpg', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='c130.Location'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='c130.Character'),
        ),
    ]
